### ISSUE TITLE
Renaming pages

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/staging.sciml.ai#4]
right now they are all menu1, menu2, etc. and they should be changed back to the original names from https://sciml.ai/

**Comment by tlienart** [comment]
done

**Comment by tlienart** [comment]
(did you want to preserve these URL too? bc it would otherwise go from e.g. `.../citing.html` to `.../citing/`; in order to keep all the "old" urls you'd have to add a few redirects, not very difficult)

**Comment by ChrisRackauckas** [comment]
It would be good. We refer to the blog posts in other repos and such and it would be good to keep that from breaking if it's not too much work.

**Comment by tlienart** [comment]
Let's open an issue, the key thing is to track down the existing URLs and make sure they all point to the right place. (a redirect page is like 3 lines of HTML so it's really not hard, I did a bunch of those for the julialang site, just need to have the right list)
