### ISSUE TITLE
blog is missing

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/staging.sciml.ai#6]
https://silly-wilson-497eb3.netlify.app/menu1/ should be https://sciml.ai/news/index.html but we need to figure out how to make it show up.

**Comment by tlienart** [comment]
Ok so it's easy to have the full list there but just note that Franklin does not yet have pagination (it's not hard to do and on my todo list, just haven't had the time); so you could either show the last X or show everything (like julialang site). which one do you prefer?

**Comment by ChrisRackauckas** [comment]
Show everything. The JuliaLang.org site is nice.

**Comment by tlienart** [comment]
:+1: maybe you guys can give it a shot copy pasting the stuff from julialang and ping me if you have trouble

**Comment by ashwani-rathee** [comment]
Actually I have already done that copy pasting thing of all the blog pages In format of year\month\date folder :)

**Comment by tlienart** [comment]
@ashwani-rathee please see what I wrote in #13
